{% set version = "0.23" %}

package:
  name: python-xlib
  version: {{ version }}

source:
  fn: python-xlib-{{ version }}.tar.bz2
  url: https://github.com/python-xlib/python-xlib/releases/download/{{ version }}/python-xlib-{{ version }}.tar.bz2
  sha256: c3deb8329038620d07b21be05673fa5a495dd8b04a2d9f4dca37a3811d192ae4

build:
  number: 0
  noarch: python
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools_scm
  run:
    - python
    - six

test:
  imports:
    - Xlib
    - Xlib.ext
    - Xlib.keysymdef
    - Xlib.protocol
    - Xlib.support
    - Xlib.xobject

about:
  home: https://github.com/python-xlib/python-xlib
  license: LGPL 2.1+
  license_family: LGPL
  license_file: LICENSE
  summary: XLib in pure Python

extra:
  recipe-maintainers:
    - jschueller
