{% set version = "0.31" %}

package:
  name: python-xlib
  version: {{ version }}

source:
  fn: python-xlib-{{ version }}.tar.bz2
  url: https://github.com/python-xlib/python-xlib/releases/download/{{ version }}/python-xlib-{{ version }}.tar.bz2
  sha256: 59a9d48b984de6df4fbf736a2010d997f668d63f1e6cf078ce55a930fbc919e6

build:
  number: 0
  noarch: python
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python >=3.3
    - setuptools >=30.3.0
    - setuptools_scm
  run:
    - python >=3.3
    - six >=1.10.0

test:
  imports:
    - Xlib
    - Xlib.ext
    - Xlib.keysymdef
    - Xlib.protocol
    - Xlib.support
    - Xlib.xobject

about:
  home: https://github.com/python-xlib/python-xlib
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: XLib in pure Python

extra:
  recipe-maintainers:
    - thewchan
    - jschueller
