{% set name = "python-xlib" %}
{% set version = "0.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-xlib-{{ version }}.tar.gz
  sha256: 74d83a081f532bc07f6d7afcd6416ec38403d68f68b9b9dc9e1f28fbf2d799e9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.3
    - setuptools >=30.3.0
    - setuptools_scm
  run:
    - python >=3.3
    - six >=1.10.0

test:
  imports:
    - Xlib
    - Xlib.ext
    - Xlib.keysymdef
    - Xlib.protocol
    - Xlib.support
    - Xlib.xobject
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-xlib/python-xlib
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: XLib in pure Python

extra:
  recipe-maintainers:
    - thewchan
    - jschueller
