{% set version = "0.29" %}

package:
  name: python-xlib
  version: {{ version }}

source:
  fn: python-xlib-{{ version }}.tar.bz2
  url: https://github.com/python-xlib/python-xlib/releases/download/{{ version }}/python-xlib-{{ version }}.tar.bz2
  sha256: 1c7ed1da3fc507e5cdb636c55b3619aac3c7a226b01860191bcba887d7ebeb6d

build:
  number: 0
  noarch: python
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools_scm
  run:
    - python
    - six

test:
  imports:
    - Xlib
    - Xlib.ext
    - Xlib.keysymdef
    - Xlib.protocol
    - Xlib.support
    - Xlib.xobject

about:
  home: https://github.com/python-xlib/python-xlib
  license: LGPL 2.1+
  license_family: LGPL
  license_file: LICENSE
  summary: XLib in pure Python

extra:
  recipe-maintainers:
    - jschueller
