travis:
  secure:
    BINSTAR_TOKEN: lyurOPmXdYGCx4H+vn1zNhNlephH25eMUMNcwc6snsHQ7mvPoekb2cjjHVnQ/3nL2nbAiC9F1P/xfZvLmAkjyIRkmNWO59wk0xdg9urjoB0cytyhzgGRk5l9eSTmngGIji6K0ye+mietuxGQFQJbM1aN1RYw9WQUlyKXzUBqMkg1rZBygBTPm0uKBHr8Yq4L9VkS3T8DSRr3gKBF8mq3NcIZeUvYCM1w/cGrPG9GiVVq5HWPF7f75OVRadeziyyScM/py3vrOy7z+di7oIr1nHTEq8UGSGVFqz+/ABeZMHyQp/Jq9SGWjGQ4GFQ+1Fu5X2lhKfrTeRvovEjGOXRnTPyne6QncdarbVKfWyFvnG/FtmlOLRf7gXOl9bVGm6uUWfV5mMiugoRqn1D8kQY3OOknGfqE0rBp4CqHVXYDnPzjEMA+aWOzSGH4joPL6WIOUwUoyCGFXAkuJFc8a/eQVALv4m1SUtVmacoDlNzyLrbPUeg/sQT3cyf4oABvPM0Hj8iGR6CmEZ4lZsLBj9bC65UpQeDaDJVIM5/La5XD4iIwKCW8oO/hvWXT5NhWQeqH9fTIR9JmgPUyVsngRxV4P5veZwP9smxjsKQMeuy6MFOqoz1ro5A/SLZrhhYWCNOM8UUFKYdaoUCgNPJ4+lop+fCO3slblZLk9zDO4idYjrI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
