travis:
  secure:
    BINSTAR_TOKEN: sHifvMBDe5SPBlVx4GZvkPdsyU+GxCtPV39+Ak4yfK1MS9eNo9w9A6XeYZDhzlpa8nPH1CWaFYe+Xr9RSWd4aaQWLvpWsmlIFYqjSqY4iabQm3Hj+9UVue4nYeZmoeUp8a4twrN0dbo4ZDp3Rb3Z3GQ7HuJ2k8yo0yDa+gL1KzT1PFHBzKrjFrUsWys1i7g5ZWLZAnyhy3nT5lxo7J82p8LNPNwq8pRe+O5JSqtjaKtykUM7Ah33c8L5OM5yODSoqm/8Sxu2Fmkp7AOGYWMH4NYQi/yNGuWcJboVLsdfctdZCmMvJSlxNqk9TUq5WmYhr3ZARGL0282vQVBO5ytb3PwsBXmA3Lo/ZeJuO1FrdXExm+2ik+hQDgGaVn8AV3ljmKIn4M4mvNEAuPupfngqT58621Grc0pTwuVinoZ6b5D92kQtz6CD6Gah+CkdWcEzCqBTJYKkLOZi2qS0LdcLCAncarGuKijcqCkgMvWs/dXv7l6QCnRs57Y3C/lJgJpa88CoPyKPkLx2K5VINGMO1UEzkv5uo8JbQdWqdokuJ76Rydl+5JWRrTn7O0u+MT7+9AMKOhf4/rM4HzDG/bOHKuEiztTdv4A/Awnz2BQ1pk7bgArRunlJBZmYmF5hxVTrMjSYP9z87FjlOAh0yxPGFHDzu+wsYsQmi2MbjLNYy9g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
